### ISSUE TITLE
Getting ERR_INVALID_MODULE_SPECIFIER with typescript ESM files

### ISSUE THREAD

**Issue by thelinuxlich** [egoist/esbuild-register#22]
I'm using esbuild-register with this command:

```json
{
 "start": "node --experimental-specifier-resolution=node -r dotenv/config -r esbuild-register src/main.ts"
}
```

It's throwing this error:

```
internal/process/esm_loader.js:74
     internalBinding('errors').triggerUncaughtException(

 TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "file:///usr/src/app/packages/admin/src/main.ts" 
  at Loader.getFormat (internal/modules/esm/loader.js:117:13)
 at Loader.getModuleJob (internal/modules/esm/loader.js:242:20)
 at Loader.import (internal/modules/esm/loader.js:176:17)
  at Object.loadESM (internal/process/esm_loader.js:68:5) {
 code: 'ERR_INVALID_MODULE_SPECIFIER'
 }
```

This doesn't happen when I use ts-node/esm instead

**Comment by sl45sms** [comment]
@Maxim-Mazurok same issue here, with the latest ts-node, downgrade from nodejs 17 to 16.
tnx for your info.
