### ISSUE TITLE
bug: node protocol unsupported

### ISSUE THREAD

**Issue by privatenumber** [egoist/esbuild-register#39]
When importing the latest `tempy`, it fails as it uses the new `node:` protocol:

```
Error: Cannot find module 'node:fs'
Require stack:
- /node_modules/.pnpm/tempy@2.0.0/node_modules/tempy/index.js
- /src/cli.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/node_modules/.pnpm/tempy@2.0.0/node_modules/tempy/index.js:1:42)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at extensions..js (/node_modules/.pnpm/esbuild-register@3.0.0_esbuild@0.13.12/node_modules/esbuild-register/dist/node.js:2703:15)
    at Object.newLoader [as .js] (/node_modules/.pnpm/esbuild-register@3.0.0_esbuild@0.13.12/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/.pnpm/tempy@2.0.0/node_modules/tempy/index.js',
    '/src/cli.ts'
  ]
```

**Comment by egoist** [comment]
Seems to be working for me, can you provide a repro?

**Comment by privatenumber** [comment]
Reproduction here: https://github.com/privatenumber/issue-reproductions/tree/master/reproductions/egoist/esbuild-register/39

**Comment by egoist** [comment]
`node:` prefix is supported by node v14.18.0 and above 😬

**Comment by privatenumber** [comment]
<details>
<summary>
It's <a href="https://nodejs.org/api/esm.html#node-imports">back-ported</a>:
</summary>

![Screen Shot 2021-11-09 at 3 22 52 AM](https://user-images.githubusercontent.com/1075694/140888149-3e70b3cf-1013-4d6f-ba10-0ab255024fd4.png)


</details>

Using the same version of Node.js, setting `"type": "module"` in `package.json`, then running `node index.js` will work fine to resolve the `node:` protocol.

I guess this doesn't work because esbuild converts `import`s to `require`s, which requires 14.18.0.

However, given esbuild-register back-ports ESM support to older versions of Node.js, I would expect it to be able to back-port `node:` as well. Surely this is easy as removing `node:` from the specifier.
