### ISSUE TITLE
esbuild-register returns error for bundle code

### ISSUE THREAD

**Issue by daniloab** [egoist/esbuild-register#65]
Im trying to build a monorepo server with esbuild. 

Inside my server package I have the following command `yarn dev` that is composed by:

```js
"scripts": {
    "build": "esbuild src/**/*.ts --bundle --platform=node --target=node16.13.2 --outdir=dist --allow-overwrite",
    "es": "node -r esbuild-register",
    "dev": "yarn es ./src/index.ts",
  },
```

And, I run this command from the root of repository with `yarn server` that is composed by the following script inside the package.json of root:

`"server": "turbo run dev --scope=@finn/server --no-deps --includeDependencies",`

But, when running returns to me the following error:

after cleaning up the repo this is the actual error

```bash
@finn/server:dev: $ node -r esbuild-register ./src/index.ts
@finn/server:dev: /Users/daniloassis/Documents/projects/dab/finn/packages/graphql/src/node/typeRegister.ts:48
@finn/server:dev:   const { nodeField, nodesField, nodeInterface } = nodeDefinitions(
@finn/server:dev:                                                    ^
@finn/server:dev: 
@finn/server:dev: TypeError: (0 , import_graphql.nodeDefinitions) is not a function
@finn/server:dev:     at null.getTypeRegister (/Users/daniloassis/Documents/projects/dab/finn/packages/graphql/src/node/typeRegister.ts:48:52)
@finn/server:dev:     at Object.<anonymous> (/Users/daniloassis/Documents/projects/dab/finn/packages/modules/src/node/typeRegistry.ts:12:5)
@finn/server:dev:     at Module._compile (node:internal/modules/cjs/loader:1101:14)
@finn/server:dev:     at Module._compile (/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/dist/node.js:2258:26)
@finn/server:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
@finn/server:dev:     at Object.newLoader [as .ts] (/Users/daniloassis/Documents/projects/dab/finn/node_modules/esbuild-register/dist/node.js:2262:9)
@finn/server:dev:     at Module.load (node:internal/modules/cjs/loader:981:32)
@finn/server:dev:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
@finn/server:dev:     at Module.require (node:internal/modules/cjs/loader:1005:19)
@finn/server:dev:     at require (node:internal/modules/cjs/helpers:102:18)
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: error Command failed with exit code 1.
@finn/server:dev: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@finn/server:dev: Error: command finished with error: exit status 1
```

Looks like that is a problem while bundling my code with some loader or something like that. am I doing something wrong or missing some configuration for esbuild-register?

My repository is open-sourced on the link below.
https://github.com/daniloab/finn

**Comment by daniloab** [comment]
fix https://github.com/daniloab/finn/pull/25

it was an wrong import inside my monorepo
